services:
  log-collector-service:
    build:
      context: ./log-collector
      dockerfile: dockerfile
    container_name: log-collector-container
    environment:
      - TZ=Europe/Istanbul
    ports: 
      - "8080:8080"    #ilk port benim bilgisayarımın portu ikinci port collector konteynırının portu.Yani benim bilgisayara 8080 den gelenleri konteynırın 8080 nine ilet demek
    volumes:
      - shared-logs:/app
    restart: always     # çökerse otomatik çalışmasını sağlar
    networks:
      - log-net
  log-generator-service:
    build:
      context: ./log-generator
      dockerfile: Dockerfile
    container_name: log-generator-container
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TZ=Europe/Istanbul
    networks:
      - log-net
    restart: always     # çökerse otomatik yeniden başlat
    depends_on:         #collector çalışmadan generatoru başlatma
      - log-collector-service  

  log-viewer-service:
    image: nginx:alpine
    container_name: netinternet-dashboard
    ports:
      - "8888:80" 
    volumes:
      - ./log-viewer:/usr/share/nginx/html:ro      #benim bilgisayarımdaki log-viewrı klasörü ile konteynırdaki web ile köprü kurar
    networks:
      - log-net 
    restart: always 
  
    

    
networks:
  log-net:
    driver: bridge

  #bilgisiyarımda ortak depolama alanı oluşturmasını söylüyorum app.json falan bunun içinde oluyor.
volumes:
  shared-logs:
  