services:
  log-collector-service:
    build:
      context: ./log-collector
      dockerfile: dockerfile
    container_name: log-collector-container
    ports: 
      - "8080:8080"
    volumes:
      - shared-logs:/app
    restart: always
    networks:
      - log-net
  log-generator-service:
    build:
      context: ./log-generator
      dockerfile: Dockerfile
    container_name: log-generator-container
    networks:
      - log-net
    depends_on:         #collector çalışmadan generatoru başlatma
      - log-collector-service  

  log-viewer-service:
    image: nginx:alpine
    container_name: netinternet-dashboard
    ports:
      - "8888:80" 
    volumes:
      - ./log-viewer:/usr/share/nginx/html:ro
    networks:
      - log-net 
    restart: always 
  
    

    
networks:
  log-net:
    driver: bridge

  #bilgisiyarımda ortak depolama alanı oluşturmasını söylüyorum app.json falan bunun içinde oluyor.
volumes:
  shared-logs:
  