FROM golang:1.26.3-alpine AS builder       
WORKDIR /app
COPY go.mod ./       
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o log-generator .
# copy deki ilk nokta bilgisayarımdaki klasör ikici nokta dockerıdaki /app
# run go mod download gerekli kütüphaneleri indiriyor ve önbelleğe alıyor hız kazandırmamız sağlıyor


FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/log-generator .
CMD ["./log-generator"]